### ISSUE TITLE
ClassLoader overlap with local development server

### ISSUE THREAD

**Issue by tomwalder** [GoogleCloudPlatform/appengine-php-sdk#1]
Seemingly, once this dependancy is installed for development, my local development server gets confused about the duplicated codebase.

I've tried a couple of simple `if(class_exists()){}` style patches, but I'm getting intermittent results - possibly an APC-style issue.

Any chance on renaming the ClassLoader? Which seems to work around the problem.

**Comment by sjlangley** [comment]
Bit of a chicken and egg problem, as the devappserver setup script pulls in the autoloader before starting the users scripts.

If the name is changed then it's probably confusing because you're not going to be certain which autoloader is registered first and is resolving one of the classes for you.

**Comment by sjlangley** [comment]
Added a check to only include the classloader once.
