### ISSUE TITLE
$val needs to be adapted past CloudStorageTools.php::L945.

### ISSUE THREAD

**Issue by sweiguny** [GoogleCloudPlatform/appengine-php-sdk#10]
https://github.com/GoogleCloudPlatform/appengine-php-sdk/blob/6bdf4bcb638782526a6969aa36528ac583cbc3da/google/appengine/api/cloud_storage/CloudStorageTools.php#L945

In most cases the value of this variable will look like this:
`2M`

And in the next few lines, arithmetic calculations are done with that variable. But you can't multiply 1024 with 2M. You will receive this warning/error:
`A non-numeric value encountered in CloudStorageTools.php on line 952`

So you should add something like this after line 946:
`$val = substr($val, 0, 1);`

**Comment by goodevilgenius** [comment]
This works fine in PHP5, but in PHP7, it issues a warning.
