### ISSUE TITLE
Call to undefined function google\net\bccomp()

### ISSUE THREAD

**Issue by hashar** [GoogleCloudPlatform/appengine-php-sdk#15]
On a php installation without the `bcmath` extension, some code path end up with:
```
Call to undefined function google\net\bccomp()
```

The reason is both `appengine/runtime/proto/ProtocolMessage.php` and `appengine/runtime/proto/Encoder.php` make use of the BCMath php extension and have `namespace google\net;`.  The `bccomp` function is thus looked up in the current namespace and obviously do not exist there.

Potentially all bc* functions could be prefixed to refer to the global namespace (ex: `\bccomp()`), but it seems easier to just require bcmath to be present. The `composer.json` file could use to be amended with:
```
{
  "require": {
    "ext-bcmath"
  }
}
```
That would at least prevent the installation when `bcmath` is unavailable.

**Comment by stevenwadejr** [comment]
I second adding this as a dependency to the `composer.json` file. I ran into this on the [Speech to Text PHP SDK](https://github.com/googleapis/google-cloud-php-speech/)

**Comment by bizsimon** [comment]
This is also required by Google Ads API and not included in its composer.json

**Comment by dsposito** [comment]
+1

**Comment by igorscandido** [comment]
Thank you very much dude, helped a lot!
