### ISSUE TITLE
Windows 7 and MemcacheUtils.php

### ISSUE THREAD

**Issue by rask** [GoogleCloudPlatform/appengine-php-sdk#2]
`MemcacheUtils.php` at line 86 raises an error and the GAE PHP SDK FCGI-process crashes in the background when attempting to access a memcache data point which is marked as unserializable, but cannot be unserialized for some reason.

The following is happening on the latest Windows GAE PHP SDK, Windows 7 and a WordPress GAE starter project:

``` text
Notice: unserialize(): Error at offset 8 of 363 bytes in C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php on line 86

Notice: unserialize(): Error at offset 8 of 768 bytes in C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php on line 86

Notice: unserialize(): Error at offset 8 of 1432 bytes in C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php on line 86

Notice: unserialize(): Error at offset 8 of 662 bytes in C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php:86) in ---\wordpress\wp-includes\option.php on line 772

Warning: Cannot modify header information - headers already sent by (output started at C:\Program Files (x86)\Google\google_appengine\php\sdk\google\appengine\runtime\MemcacheUtils.php:86) in ---\wordpress\wp-includes\option.php on line 773
```

The following section in `MemcacheUtils.php` triggers the notice:

``` php
case self::TYPE_PHP_SERIALIZED:
        return unserialize($value);
```

It attempts to unserialize the value, but the flag is seemingly not correct or something.

**Comment by Rask** [comment]
The error disappears when I remove

`extension = "curl.so"`

form the `php.ini` of the project. Any idea why that happens? cURL Lite doesn't work either.

**Comment by sjlangley** [comment]
What caching plugin are you using?

**Comment by rask** [comment]
This error is happening inside App Engine itself now (the production server). Even more fierce than local Windows development environment. Windows produces 1-5 notices per page load, on the live server there seems to be 14-20 per page load.

The only cache related plugin active on the installation is an in-house .mo/.po localization file loader (caches the localization files to Memcache to keep things speedy).

Other than that I'm using regular WordPress transients and the WP Memcache object cache system to cache data.

I'll investigate whether the issue is happening because of that in-house .mo cacher plugin.
