### ISSUE TITLE
Support autoloading

### ISSUE THREAD

**Issue by hdp617** [GoogleCloudPlatform/appengine-php-sdk#22]
In PHP 5.5, users can write code like [0]
```
// Simple HTTP GET and PUT operators.
$app->get('/memcache/{key}', function ($key) {
    # [START gae_memcache_get]
    $memcache = new Memcache;
    return $memcache->get($key);
    # [END gae_memcache_get]
});
```
without importing the `Memcache` class from the SDK.

Can we achieve this in PHP 7.x with autoloading? @bshaffer 

cc: @hazemm96

[0] https://github.com/GoogleCloudPlatform/php-docs-samples/blob/eec5f5ca0c7757a9ef7afaeeeaa3c60228393f44/appengine/php55/memcache/app.php#L55

**Comment by hazemm96** [comment]
Asked this to mtraver a while ago. We can't and he said we shouldn't
attempt to support it. So as mentioned in the doc just asking users to
modify their composer.json should be good enough because what's in the
composer.json is installed automatically.

**Comment by hdp617** [comment]
Are we talking about the same thing. I'm referring to autoloading the classes provided by the SDK, not installing the SDK on behalf of users if it's not in `composer.json`. cc @mtraver

**Comment by mtraver** [comment]
Right, those are different things. Autoloading is fine. What I said is that we shouldn't ship the SDK with the runtime like we do for PHP 5.5. Users must include it in `composer.json`.

**Comment by hazemm96** [comment]
My mistake, back to Huy's question. Is it worth supporting autoloading for php7+? It doesn't seem to work today
