### ISSUE TITLE
Current stable release on packagist fails

### ISSUE THREAD

**Issue by cedricziel** [GoogleCloudPlatform/appengine-php-sdk#5]
I discovered the custom autoloader in ``google/runtime/autoloader.php`` on the last stable release fails.

Can you tag a new release please? - The issue has been resolved by 725347f9e9321fc6fe839e58759cb95716c4febd already.

**Comment by bshaffer** [comment]
@sjlangley what is the way we typically handle tagging releases here? Is there any reason we can't just tag `1.9.26`?

**Comment by sjlangley** [comment]
I'll try and fix it today

**Comment by sjlangley** [comment]
Pushed up 1.9.30 release
